### ISSUE TITLE
u8(255.0) yields Overflow

### ISSUE THREAD

**Issue by federicomenaquintero** [japaric/cast.rs#23]
```rust
use cast::u8;

fn main() {
    println!("{:?}", u8(255.0)); // yields Overflow
}
```

It should be `Ok(255)`, of course :smiley:

**Comment by oherrala** [comment]
This conversion error happens on line 299 of lib.rs where the transmutes returns a value 254.99999999999997 for `max` and then on line 301  `src` is compared to `max` as `255 > 254.99999999999997` which of course is true and the whole `cast` functions return `Error::Overflow` on line 303.

https://github.com/japaric/cast.rs/blob/cd85b6648222c74a465e716a5d56199f23e74535/src/lib.rs#L293-L304

This bug was introduced in 3f0bf8be7096f4d3fbdde3cff4182d6329b1286f to fix issue #15.
